// Code generated by MockGen. DO NOT EDIT.
// Source: weather.go
//
// Generated by this command:
//
//	mockgen -source=weather.go -package=mock -destination=mock/weather.go
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	weather "github.com/deadlysurgeon/weather/weather"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// At mocks base method.
func (m *MockService) At(lat, long string) (weather.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "At", lat, long)
	ret0, _ := ret[0].(weather.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// At indicates an expected call of At.
func (mr *MockServiceMockRecorder) At(lat, long any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "At", reflect.TypeOf((*MockService)(nil).At), lat, long)
}
